import type { ModelOffer } from "../../domain/catalog";

// DEMO FIXTURE ONLY. Production components must read through catalogRepository.

export const MODEL_OFFERS: ModelOffer[] = [
  {
    id: "claude-sonnet",
    name: "Claude Sonnet",
    modelId: "claude-sonnet",
    family: "Anthropic",
    summary: "复杂代码、长上下文与代理任务",
    modality: "语言",
    kind: "闭源 API",
    offerType: "统一余额",
    tags: ["代码", "工具调用", "长文本"],
    specLabel: "上下文",
    specValue: "200K",
    protocol: "Anthropic / OpenAI",
    price: "¥ 12.00",
    unit: "每百万输入 Token 起",
    route: "稳定路由 · 亚太",
    health: "99.92%",
    meta: "3 个可用来源",
    sources: [
      { name: "Moyusi 稳定线路", mode: "统一余额", price: "¥ 12.00 / M", health: "99.92%", note: "亚太优先 · 不留存正文", recommended: true },
      { name: "合作中转站 A（演示）", mode: "统一余额", price: "¥ 10.80 / M", health: "99.71%", note: "价格优先 · 最近验证 6 分钟" },
      { name: "你的 Anthropic Key", mode: "BYOK", price: "外部计费", health: "直连", note: "凭证只保存在本地" },
    ],
  },
  {
    id: "gpt-coding",
    name: "GPT · Coding",
    modelId: "gpt-coding",
    family: "OpenAI",
    summary: "工程实现、代码审查与多步骤工作",
    modality: "语言",
    kind: "闭源 API",
    offerType: "统一余额",
    tags: ["代码", "推理", "Responses"],
    specLabel: "上下文",
    specValue: "400K",
    protocol: "Responses / Chat",
    price: "¥ 8.20",
    unit: "每百万输入 Token 起",
    route: "稳定路由 · 全球",
    health: "99.95%",
    meta: "3 个可用来源",
    sources: [
      { name: "Moyusi 稳定线路", mode: "统一余额", price: "¥ 8.20 / M", health: "99.95%", note: "Responses 完整兼容", recommended: true },
      { name: "合作中转站 B（演示）", mode: "统一余额", price: "¥ 6.90 / M", health: "99.62%", note: "成本优先 · 全球入口" },
      { name: "你的 OpenAI Key", mode: "BYOK", price: "外部计费", health: "直连", note: "使用官方账户结算" },
    ],
  },
  {
    id: "gemini-flash",
    name: "Gemini Flash",
    modelId: "gemini-flash",
    family: "Google",
    summary: "快速分析、长文档与低延迟调用",
    modality: "语言",
    kind: "闭源 API",
    offerType: "BYOK",
    tags: ["低延迟", "长文本", "多模态"],
    specLabel: "上下文",
    specValue: "1M",
    protocol: "OpenAI / Google",
    price: "外部计费",
    unit: "也可使用统一余额线路",
    route: "本地直连",
    health: "99.81%",
    meta: "2 个可用来源",
    sources: [
      { name: "你的 Google AI Key", mode: "BYOK", price: "外部计费", health: "直连", note: "凭证只保存在本地", recommended: true },
      { name: "Moyusi 通用线路", mode: "统一余额", price: "¥ 1.20 / M", health: "99.81%", note: "OpenAI-compatible" },
    ],
  },
  {
    id: "qwen-coder-open",
    name: "Qwen Coder",
    modelId: "qwen-coder-open",
    family: "Qwen",
    summary: "中文编程、仓库理解与工具调用",
    modality: "语言",
    kind: "开放权重",
    offerType: "共享算力",
    tags: ["代码", "中文", "可部署"],
    specLabel: "上下文",
    specValue: "128K",
    protocol: "OpenAI-compatible",
    price: "¥ 0.86",
    unit: "每百万输入 Token 起",
    route: "FP8 · vLLM · 新加坡",
    health: "99.76%",
    meta: "3 种部署方式",
    sources: [
      { name: "共享 GPU 集群", mode: "共享算力", price: "¥ 0.86 / M", health: "WARM", note: "FP8 · vLLM · 新加坡", recommended: true },
      { name: "专属 GPU 实例", mode: "专属算力", price: "¥ 5.80 / h", health: "待创建", note: "按小时结算 · 支持自动休眠" },
      { name: "连接你的端点", mode: "自有端点", price: "外部计费", health: "待探测", note: "支持 vLLM / SGLang" },
    ],
  },
  {
    id: "deepseek-reasoning-open",
    name: "DeepSeek Reasoning",
    modelId: "deepseek-reasoning-open",
    family: "DeepSeek",
    summary: "深度推理、规划和高性价比任务",
    modality: "语言",
    kind: "开放权重",
    offerType: "共享算力",
    tags: ["推理", "可部署", "低成本"],
    specLabel: "上下文",
    specValue: "128K",
    protocol: "OpenAI-compatible",
    price: "¥ 1.10",
    unit: "每百万输入 Token 起",
    route: "BF16 · SGLang · 东京",
    health: "99.68%",
    meta: "2 种部署方式",
    sources: [
      { name: "弹性共享集群", mode: "共享算力", price: "¥ 1.10 / M", health: "COLD", note: "冷启动约 28 秒", recommended: true },
      { name: "连接你的端点", mode: "自有端点", price: "外部计费", health: "待探测", note: "模型身份需要校验" },
    ],
  },
  {
    id: "gpt-image",
    name: "GPT Image",
    modelId: "gpt-image",
    family: "OpenAI",
    summary: "高质量文生图、编辑与文字渲染",
    modality: "图片",
    kind: "闭源 API",
    offerType: "统一余额",
    tags: ["文生图", "图像编辑", "文字渲染"],
    specLabel: "输出规格",
    specValue: "最高 4K",
    protocol: "Images API",
    price: "¥ 0.28",
    unit: "每张起 · 按规格计费",
    route: "高质量线路 · 全球",
    health: "99.73%",
    meta: "2 个可用来源",
    sources: [
      { name: "Moyusi 高质量线路", mode: "统一余额", price: "¥ 0.28 / 张起", health: "99.73%", note: "支持编辑与透明背景", recommended: true },
      { name: "你的 OpenAI Key", mode: "BYOK", price: "外部计费", health: "直连", note: "使用官方账户结算" },
    ],
  },
  {
    id: "gemini-image",
    name: "Gemini Image",
    modelId: "gemini-image",
    family: "Google",
    summary: "多轮图像创作、理解与局部修改",
    modality: "图片",
    kind: "闭源 API",
    offerType: "统一余额",
    tags: ["多轮编辑", "参考图", "图像理解"],
    specLabel: "输入图片",
    specValue: "最多 8 张",
    protocol: "Google / OpenAI",
    price: "¥ 0.22",
    unit: "每张起 · 按规格计费",
    route: "低延迟线路 · 亚太",
    health: "99.69%",
    meta: "2 个可用来源",
    sources: [
      { name: "Moyusi 亚太线路", mode: "统一余额", price: "¥ 0.22 / 张起", health: "99.69%", note: "适合多轮编辑", recommended: true },
      { name: "你的 Google AI Key", mode: "BYOK", price: "外部计费", health: "直连", note: "凭证只保存在本地" },
    ],
  },
  {
    id: "flux-kontext",
    name: "FLUX · Kontext",
    modelId: "flux-kontext",
    family: "Black Forest Labs",
    summary: "角色一致性、参考图编辑与风格控制",
    modality: "图片",
    kind: "开放权重",
    offerType: "共享算力",
    tags: ["角色一致", "参考图", "可部署"],
    specLabel: "输出规格",
    specValue: "最高 2K",
    protocol: "Images-compatible",
    price: "¥ 0.12",
    unit: "每张起 · 共享算力",
    route: "BF16 · ComfyUI · 东京",
    health: "WARM",
    meta: "3 种部署方式",
    sources: [
      { name: "共享图像集群", mode: "共享算力", price: "¥ 0.12 / 张起", health: "WARM", note: "已缓存常用工作流", recommended: true },
      { name: "专属 ComfyUI", mode: "专属算力", price: "¥ 4.60 / h", health: "待创建", note: "自定义节点需安全检查" },
      { name: "连接你的工作流", mode: "自有端点", price: "外部计费", health: "待探测", note: "导入 API workflow" },
    ],
  },
  {
    id: "qwen-image",
    name: "Qwen Image",
    modelId: "qwen-image",
    family: "Qwen",
    summary: "中文文字生成、海报与商品图创作",
    modality: "图片",
    kind: "开放权重",
    offerType: "共享算力",
    tags: ["中文文字", "海报", "可部署"],
    specLabel: "输出规格",
    specValue: "最高 2K",
    protocol: "Images-compatible",
    price: "¥ 0.08",
    unit: "每张起 · 共享算力",
    route: "FP8 · ComfyUI · 新加坡",
    health: "WARM",
    meta: "2 种部署方式",
    sources: [
      { name: "共享图像集群", mode: "共享算力", price: "¥ 0.08 / 张起", health: "WARM", note: "中文提示词优化", recommended: true },
      { name: "连接你的工作流", mode: "自有端点", price: "外部计费", health: "待探测", note: "支持 ComfyUI API" },
    ],
  },
  {
    id: "seedance-video",
    name: "Seedance",
    modelId: "seedance-video",
    family: "ByteDance",
    summary: "高动态文生视频与图生视频",
    modality: "视频",
    kind: "闭源 API",
    offerType: "统一余额",
    tags: ["文生视频", "图生视频", "镜头运动"],
    specLabel: "最高时长",
    specValue: "10 秒",
    protocol: "Video Tasks API",
    price: "¥ 0.52",
    unit: "每秒起 · 按分辨率计费",
    route: "稳定线路 · 亚太",
    health: "98.96%",
    meta: "2 个可用来源",
    sources: [
      { name: "Moyusi 稳定线路", mode: "统一余额", price: "¥ 0.52 / 秒起", health: "98.96%", note: "任务队列约 18 秒", recommended: true },
      { name: "合作中转站 C（演示）", mode: "统一余额", price: "¥ 0.46 / 秒起", health: "98.41%", note: "成本优先 · 排队时间波动" },
    ],
  },
  {
    id: "veo-video",
    name: "Veo",
    modelId: "veo-video",
    family: "Google",
    summary: "电影感镜头、音画生成与提示词遵循",
    modality: "视频",
    kind: "闭源 API",
    offerType: "BYOK",
    tags: ["电影感", "音画", "高质量"],
    specLabel: "最高时长",
    specValue: "8 秒",
    protocol: "Google Video API",
    price: "外部计费",
    unit: "也可选择统一余额线路",
    route: "本地直连",
    health: "98.72%",
    meta: "2 个可用来源",
    sources: [
      { name: "你的 Google AI Key", mode: "BYOK", price: "外部计费", health: "直连", note: "凭证只保存在本地", recommended: true },
      { name: "Moyusi 高质量线路", mode: "统一余额", price: "¥ 2.80 / 秒起", health: "98.72%", note: "生产版显示实时排队" },
    ],
  },
  {
    id: "kling-video",
    name: "Kling Video",
    modelId: "kling-video",
    family: "Kuaishou",
    summary: "人物动作、运镜与较长视频片段",
    modality: "视频",
    kind: "闭源 API",
    offerType: "统一余额",
    tags: ["人物动作", "运镜", "图生视频"],
    specLabel: "最高时长",
    specValue: "10 秒",
    protocol: "Video Tasks API",
    price: "¥ 0.64",
    unit: "每秒起 · 按模式计费",
    route: "通用线路 · 中国区",
    health: "98.88%",
    meta: "2 个可用来源",
    sources: [
      { name: "Moyusi 通用线路", mode: "统一余额", price: "¥ 0.64 / 秒起", health: "98.88%", note: "支持任务状态回调", recommended: true },
      { name: "你的供应商 Key", mode: "BYOK", price: "外部计费", health: "直连", note: "本地绑定凭证" },
    ],
  },
  {
    id: "wan-video-open",
    name: "Wan Video",
    modelId: "wan-video-open",
    family: "Wan",
    summary: "开放权重的视频生成与自有工作流部署",
    modality: "视频",
    kind: "开放权重",
    offerType: "共享算力",
    tags: ["开放权重", "ComfyUI", "可部署"],
    specLabel: "最高时长",
    specValue: "5 秒",
    protocol: "Async Tasks API",
    price: "¥ 0.18",
    unit: "每秒起 · 共享算力",
    route: "FP8 · ComfyUI · 新加坡",
    health: "WARM",
    meta: "3 种部署方式",
    sources: [
      { name: "共享视频集群", mode: "共享算力", price: "¥ 0.18 / 秒起", health: "WARM", note: "平均排队约 32 秒", recommended: true },
      { name: "专属 GPU 实例", mode: "专属算力", price: "¥ 7.20 / h", health: "待创建", note: "按小时结算 · 可自动休眠" },
      { name: "连接你的工作流", mode: "自有端点", price: "外部计费", health: "待探测", note: "支持 ComfyUI API" },
    ],
  },
];
